language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements-test.txt
before_script:
  - "flake8 ."
  - "black -l 99 --check --verbose ."
# command to run tests
script:
  - python -m pytest --cov
after_success:
  - codecov
